[package]
name = "vopono"
description = "Launch applications via VPN tunnels using temporary network namespaces"
version = "0.1.2"
authors = ["James McMurray <jamesmcm03@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/jamesmcm/vopono"
homepage = "https://github.com/jamesmcm/vopono"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1"
directories-next = "1"
log = "0.4"
pretty_env_logger = "0.4"
clap = "2"
which = "4"
users = "0.10"
nix = "0.17"
serde = {version = "1", features = ["derive"]}
csv = "1"
dialoguer = "0.6"
regex = "1"
ron = "0.6"
walkdir = "2"
rand = "0.7"
toml = "0.5"
chrono = "0.4"
compound_duration = "1"
